[package]
name = "stupdedup"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
itertools = "0.14.0"
rayon = "1.10.0"
seahash = "4.1.0"
walkdir = "2.5.0"
